spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: ABC
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 80
logging:
  level:
    com.testall.demo.dao : debug