spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: ABC
    password: Aa123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 80
logging:
  level:
    com.testall.demo.dao : debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

  #文件存储路径
filepath: D:/file/
